### ISSUE TITLE
Support for Redmine 2.1.x

### ISSUE THREAD

**Issue by waifung0207** [splendeo/redmine_project_filtering#6]
Receive message like this when trying to deploy into my Redmine system (v2.1.2)

> rake aborted!
> cannot load such file -- dispatcher

Would like to see if it is possible to upgrade this plugin, as this will be very useful when lots of projects are created in the portal. 

Thanks in advance.

**Comment by kikito** [comment]
Hi waifung0207,

Please include:

a) The rake command you were executing when you got this error
b) The complete error log (you can get it by adding -t to rake : `rake -t ...`)
c) A list of any other plugins that you might have installed.

**Comment by waifung0207** [comment]
The rake command I am using is:

> sudo rake redmine:plugins:migrate RAILS_ENV=production NAME=redmine_project_filtering

And in fact when I clone the master branch and rake it directly in my server, this error message comes out:

> rake aborted!
> /usr/share/redmine/plugins/redmine_project_filtering/init.rb:30: invalid multibyte char (US-ASCII)
> /usr/share/redmine/plugins/redmine_project_filtering/init.rb:30: invalid multibyte char (US-ASCII)
> /usr/share/redmine/plugins/redmine_project_filtering/init.rb:30: syntax error, unexpected $end, expecting keyword_end
>   author 'Enrique GarcÃ­a Cota'
>                         ^
> Tasks: TOP => redmine:plugins:migrate => environment

But then found a solution on [Stackoverflow](http://stackoverflow.com/questions/3678172/ruby-1-9-invalid-multibyte-char-us-ascii), and type the line "# encoding: utf-8" on top of init.rb.

However then I saw the error message in my first post. Full log as below:

> *\* Invoke redmine:plugins:migrate (first_time)
> *\* Invoke environment (first_time)
> *\* Execute environment
> rake aborted!
> cannot load such file -- dispatcher
> /var/lib/gems/1.9.1/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `require'
> /var/lib/gems/1.9.1/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in`block in require'
> /var/lib/gems/1.9.1/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:236:in `load_dependency'
> /var/lib/gems/1.9.1/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in`require'
> /usr/share/redmine/plugins/redmine_project_filtering/init.rb:4:in `<top (required)>'
> /var/lib/gems/1.9.1/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in`require'
> /var/lib/gems/1.9.1/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `block in require'
> /var/lib/gems/1.9.1/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:236:in`load_dependency'
> /var/lib/gems/1.9.1/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `require'
> /usr/share/redmine/lib/redmine/plugin.rb:130:in`block in load'
> /usr/share/redmine/lib/redmine/plugin.rb:121:in `each'
> /usr/share/redmine/lib/redmine/plugin.rb:121:in`load'
> /usr/share/redmine/config/initializers/30-redmine.rb:13:in `<top (required)>'
> /var/lib/gems/1.9.1/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:245:in`load'
> /var/lib/gems/1.9.1/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:245:in `block in load'
> /var/lib/gems/1.9.1/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:236:in`load_dependency'
> /var/lib/gems/1.9.1/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:245:in `load'
> /var/lib/gems/1.9.1/gems/railties-3.2.8/lib/rails/engine.rb:588:in`block (2 levels) in class:Engine'
> /var/lib/gems/1.9.1/gems/railties-3.2.8/lib/rails/engine.rb:587:in `each'
> /var/lib/gems/1.9.1/gems/railties-3.2.8/lib/rails/engine.rb:587:in`block in class:Engine'
> /var/lib/gems/1.9.1/gems/railties-3.2.8/lib/rails/initializable.rb:30:in `instance_exec'
> /var/lib/gems/1.9.1/gems/railties-3.2.8/lib/rails/initializable.rb:30:in`run'
> /var/lib/gems/1.9.1/gems/railties-3.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
> /var/lib/gems/1.9.1/gems/railties-3.2.8/lib/rails/initializable.rb:54:in`each'
> /var/lib/gems/1.9.1/gems/railties-3.2.8/lib/rails/initializable.rb:54:in `run_initializers'
> /var/lib/gems/1.9.1/gems/railties-3.2.8/lib/rails/application.rb:136:in`initialize!'
> /var/lib/gems/1.9.1/gems/railties-3.2.8/lib/rails/railtie/configurable.rb:30:in `method_missing'
> /usr/share/redmine/config/environment.rb:14:in`<top (required)>'
> /var/lib/gems/1.9.1/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `require'
> /var/lib/gems/1.9.1/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in`block in require'
> /var/lib/gems/1.9.1/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:236:in `load_dependency'
> /var/lib/gems/1.9.1/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in`require'
> /var/lib/gems/1.9.1/gems/railties-3.2.8/lib/rails/application.rb:103:in `require_environment!'
> /var/lib/gems/1.9.1/gems/railties-3.2.8/lib/rails/application.rb:295:in`block (2 levels) in initialize_tasks'
> /var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
> /var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`block in execute'
> /var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
> /var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`execute'
> /var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
> /usr/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
> /var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
> /var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:176:in`block in invoke_prerequisites'
> /var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `each'
> /var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:174:in`invoke_prerequisites'
> /var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
> /usr/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
> /var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
> /var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in`invoke'
> /var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
> /var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`block (2 levels) in top_level'
> /var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
> /var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`block in top_level'
> /var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
> /var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in`top_level'
> /var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
> /var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
> /var/lib/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
> /var/lib/gems/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in`<top (required)>'
> /usr/local/bin/rake:19:in `load'
> /usr/local/bin/rake:19:in`<main>'
> Tasks: TOP => redmine:plugins:migrate => environment

**Comment by waifung0207** [comment]
some other plugins I have installed:
- redmine_knowledgebase
- redmine_project_filtering
- redmine_inline_attach_screenshot
- redmine_lightbox
- redmine_user_issues

**Comment by kikito** [comment]
Hi,

Sorry about the non-ascii characters of my name. I've added the magical utf8 comment to the initialize.rb file.

I confess I don't quite understand where your 'dispatcher' error comes from.

The only thing related with this error that I could find is this old redmine issue: http://www.redmine.org/issues/11035

Down the thread of that list, someone recommends adding the 'user' and 'principal' dependencies if attempting to modify project, as we do on this plugin.

Please try adding them on initialize.rb and let us know if that solves that issue:

``` ruby
# around line 16 in initialize.rb
require_dependency 'project'
require_dependency 'principal' # add this
require_dependency 'user' # add this
Project.send(:include, RedmineProjectFiltering::Patches::ProjectPatch)
```

**Comment by waifung0207** [comment]
I have tried adding the 2 lines, but same thing happens.

This seems to be a general issue of Redmine plugins that do not support v2.x, as I have founded this message when trying to install other plugins. 

Thanks very much for your reply though.

**Comment by kikito** [comment]
I'm sorry we could not help you any further. I will close this issue now then. If you find the solution, feel free to reopen this.
