### ISSUE TITLE
Error in 2.3.1

### ISSUE THREAD

**Issue by R-i-c-k-y** [splendeo/redmine_project_filtering#8]
Solved migration problems with some changes:

[init.rb]
![1](https://f.cloud.github.com/assets/432347/1051306/b7e86898-10c8-11e3-8dab-0f285ca2416b.png)

changed named_scope to _scope_
![sc1](https://f.cloud.github.com/assets/432347/1051310/d0a036cc-10c8-11e3-91fa-8c0c53a53110.png)
![sc2](https://f.cloud.github.com/assets/432347/1051311/d4c932d0-10c8-11e3-9b3e-95cd45e91f85.png)

started Redmine, but when I open Projects page I get this error:
![error_](https://f.cloud.github.com/assets/432347/1051321/ecc82bc0-10c8-11e3-86c5-127766e00d20.png)

any hint?
Thanks for your work

**Comment by fjuan** [comment]
If you found a bug, please fork the project and ask for a pull request. I'll be glad to add your changes to the projecto
